#!/usr/bin/env python3

################################################
#
# Imports 
#
################################################
import wave
import time
from pynput import keyboard
from pygame import mixer
import time
import random

lettereDaUsare = [ 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'i', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'z' ]

################################################
#
# Define letter audio files 
#
################################################
audio = {}
audio['a'] = './audio/a.ogg'
audio['e'] = './audio/e.ogg'
audio['i'] = './audio/i.ogg'
audio['o'] = './audio/o.ogg'
audio['u'] = './audio/u.ogg'
audio['b'] = './audio/b.ogg'
audio['c'] = './audio/c.ogg'
audio['d'] = './audio/d.ogg'
audio['f'] = './audio/f.ogg'
audio['g'] = './audio/g.ogg'
audio['l'] = './audio/l.ogg'
audio['m'] = './audio/m.ogg'
audio['n'] = './audio/n.ogg'
audio['p'] = './audio/p.ogg'
audio['q'] = './audio/q.ogg'
audio['r'] = './audio/r.ogg'
audio['s'] = './audio/s.ogg'
audio['t'] = './audio/t.ogg'
audio['v'] = './audio/v.ogg'
audio['z'] = './audio/z.ogg'

audio['intro'] = './audio/intro.ogg'
audio['si'] = './audio/si.ogg'
audio['no'] = './audio/no.ogg'
audio['piano-si'] = './audio/piano-si.ogg'
audio['piano-no'] = './audio/piano-no.ogg'
audio['voce-nono'] = './audio/voce-nono.ogg'


################################################
#
# Init audio 
#
################################################
mixer.init()

def playAudioTutto(name) :
    print("Looking for '%s' per suonarlo tutto" % name)
    if name in audio :
        mixer.music.stop()
        audioName = audio[name]
        print("Found '%s': playing" % audioName)
        mixer.music.load(audioName)
        mixer.music.play(1, 0.0)
        while mixer.music.get_busy() == True:
            time.sleep(0.01)
            continue

def playAudio(name) :
    print("Looking for '%s'" % name)
    if name in audio :
        audioName = audio[name]
        print("Found '%s': playing" % audioName)
        mixer.music.load(audioName)
        mixer.music.play()

def on_press(key):
    print (key)
    try:
        if len(key.char) == 1 :
            print("'%s'" % key.char)
            playAudio(key.char)
            if key.char == giusta :
                playAudioTutto('piano-si')
                listener.stop()
            else :
                playAudio('voce-nono')
    except:
        print("not a letter")

while True:
    # Inizia un indovinello
    playAudioTutto('intro')
    # Scegli una lettera a caso
    lett = random.choice(lettereDaUsare)
    print("Ho scelto la lettera '%s'" % lett)
    playAudioTutto(lett)
    global giusta
    global continua
    giusta = lett
    continua = True
    with keyboard.Listener(on_press=on_press) as listener:
        listener.join()
        playAudioTutto('si')
        time.sleep(1)


